# greetd config (text greeter via agreety)
[terminal]
vt = 1

[default_session]
# run a minimal text greeter that, after successful login,
# executes our session command.
command = "agreety --cmd start-sway"
user = "greeter"
